### ISSUE TITLE
Server Major Bug - Ticking Player Bug

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [KenLPham/ArcadeMod#1]
https://gist.github.com/P3rf3ctXZer0/9757b3de185c0e80cfa4bb0796e11e1c

**Comment by KenLPham** [comment]
Minecraft version?
Mod version?

**Comment by P3rf3ctXZer0** [comment]
Open Gist. Everything you need is there.

**Comment by KenLPham** [comment]
doesn't have either mod or minecraft version

**Comment by P3rf3ctXZer0** [comment]
Sorry I thought I included the full crashlog - I suck my bad.
