### ISSUE TITLE
Crash on game loading

### ISSUE THREAD

**Issue by brisingraerowing** [KenLPham/ArcadeMod#4]
[Crash Log](https://gist.github.com/BrisingrAerowing/f1279ba2cb45f52940d77ef406dfb5a4)

Version: 2.1.3

It seems that the prizelist.json file can't be extracted as the directory does not actually exist. You probably have to create it first.

**Comment by KenLPham** [comment]
~~Please post full crash log~~

The check for the directory is after trying to load the prize list. A temporary fix is to start Minecraft again and it will create the prizelist file
